### ISSUE TITLE
Criar documento de Metodologias

### ISSUE THREAD

**Issue by IanPSRocha** [fga-eps-mds/2023.2-MeasureSoftGram-DOC#10]
## Descrição
Criar um arquivo que descreva as metodologias aplicadas durante o projeto.

## Tarefas
O documento deve descrever:
- Metodologia de Desenvolvimento
- Metodologia de Gerência
- Ferramentas utilizadas

## Critérios de Aceitação

- [x]  Documento markdown na pasta docs do projeto
- [x]  Possuir Versionamento
- [x]  Possuir Referências
- [x]  Estar no tópico de Planejamento no GitPages

**Comment by joaobisi** [comment]
Documento criado e adicionado ao Github Pages
