### ISSUE TITLE
Criar dojo React para auxiliar equipe de MDS

### ISSUE THREAD

**Issue by oCaioOliveira** [fga-eps-mds/2023.2-MeasureSoftGram-DOC#17]
## Descrição da Issue

Criar um dojo para auxiliar a equipe de MDS para entender melhor o *framework* React usada no projeto.

## Tarefas:
- [x] Criar a apresentação dojo de React.
- [x] Reunir com a equipe de MDS para apresentar o dojo para repassar conhecimento.

## Critérios de Aceitação

- [ ] Link para apresentação dojo de React.
- [ ] Link para o vídeo da apresentação com o dojo e dúvidas da equipe.

**Comment by joaobisi** [comment]
[Link para apresentação dojo de React](https://www.canva.com/design/DAFw3O8mrEA/z6CiZDOKtrX4xYVAz69sEA/edit?utm_content=DAFw3O8mrEA&utm_campaign=designshare&utm_medium=link2&utm_source=sharebutton])
