### ISSUE TITLE
Deploy Backend

### ISSUE THREAD

**Issue by vitorekr** [fga-eps-mds/2023.2-MeasureSoftGram-DOC#22]
## Descrição da Issue

Fazer o *deploy* do *Back-end* do projeto na plataforma Vercel.

## Tarefas:
- [x] Criar o projeto na plataforma Railway para o projeto.

## Critérios de Aceitação

- [x] Gerar o link para acesso do *Backend* do projeto para acesso da equipe.

**Comment by oCaioOliveira** [comment]
Link do Back-end: https://2023-2-measuresoftgram-service-production.up.railway.app/admin/
