### ISSUE TITLE
HOTFIX: Problema ao logar com Github no Deploy

### ISSUE THREAD

**Issue by IanPSRocha** [fga-eps-mds/2023.2-MeasureSoftGram-DOC#27]
## Descrição
Atualmente, o cliente não consegue logar na aplicação usando sua conta github:
![image](https://github.com/fga-eps-mds/2023.2-MeasureSoftGram-DOC/assets/42422835/f0890176-2b8e-465b-aac9-021bc3854462)

## Tarefas
- Corrigir problema de autenticação do github

## Critérios de Aceitação

- [ ]  Conseguir realizar o login na aplicação com sua conta do Github

**Comment by oCaioOliveira** [comment]
Problema foi corrigido e será criado um documento de tutorial para auxiliar próximos contribuintes ao projeto
