### ISSUE TITLE
FIX - Reajustar o relacionamento de métricas e medidas.

### ISSUE THREAD

**Issue by IanPSRocha** [fga-eps-mds/2023.2-MeasureSoftGram-DOC#43]
## Tarefas
- Criar uma tabela no banco de dados representando o relacionamento N:M entre Medidas e Métricas
- Atualizar as Model's do sistema representando esse relacionamento 
- Realizar as Migrations para atualização do banco

**Comment by joaobisi** [comment]
No Service, em src/measures/models.py, já está estabelecido relacionamento N:M entre métricas e medidas, e as consultas condizem com essa implementação. Portanto, foi identificado que o defeito já foi corrigido previamente.
