### ISSUE TITLE
US32 - Baixar relatórios sobre os dados do produto

### ISSUE THREAD

**Issue by IanPSRocha** [fga-eps-mds/2023.2-MeasureSoftGram-DOC#61]
## Descrição

Eu, como usuário, desejo obter os dados do produto, seja da sua visão geral ou dos dados em seus repositórios, em um arquivo no formato CSV. Deve ser possível exportar os dados em todos os gráficos em linha.

## Tarefas

**Exportar um arquivo CSV com os dados do produto do gráfico de linha na aba de visão geral do produto sobre o comportamento observado do produto**

Front-end:

- Criar botão;
- Criar lógica para organizar os dados do produto do gráfico de linha na aba de visão geral do produto sobre o comportamento observado do produto;
- Filtrar esses dados com base nas datas selecionadas no Front-end pelo usuário;
- Baixar o arquivo CSV com esses dados na máquina do usuário.

**Exportar um arquivo CSV com os dados do produto do gráfico de linha na aba de repositórios do produto sobre o histórico das características**

Front-end:

- Criar botão;
- Criar lógica para organizar os dados do produto do gráfico de linha na aba de repositórios do produto sobre o histórico das características;
- Filtrar esses dados com base nas datas selecionadas no Front-end pelo usuário;
- Baixar o arquivo CSV com esses dados na máquina do usuário.

**Exportar um arquivo CSV com os dados do produto do gráfico de linha na aba de repositórios do produto sobre as sub-características**

Front-end:

- Criar botão;
- Criar lógica para organizar os dados do produto do gráfico de linha na aba de repositórios do produto sobre as sub-características;
- Filtrar esses dados com base nas datas selecionadas no Front-end pelo usuário;
- Baixar o arquivo CSV com esses dados na máquina do usuário.

**Exportar um arquivo CSV com os dados do produto do gráfico de linha na aba de repositórios do produto sobre as medidas**

Front-end:

- Criar botão;
- Criar lógica para organizar os dados do produto do gráfico de linha na aba de repositórios do produto sobre as medidas;
- Filtrar esses dados com base nas datas selecionadas no Front-end pelo usuário;
- Baixar o arquivo CSV com esses dados na máquina do usuário.

**Exportar um arquivo CSV com os dados do produto do gráfico de linha na aba de repositórios do produto sobre as métricas**

Front-end:

- Criar botão;
- Criar lógica para organizar os dados do produto do gráfico de linha na aba de repositórios do produto sobre as métricas;
- Filtrar esses dados com base nas datas selecionadas no Front-end pelo usuário;
- Baixar o arquivo CSV com esses dados na máquina do usuário.

## Critérios de Aceitação

**Visualização Esperada**

- [x] Na aba de visão geral do produto, no gráfico de linha sobre o comportamento observado do produto, deve ser possível visualizar botão para exportar dados sobre o produto.
- [x] Na aba de repositórios do produto, no gráfico de linha sobre o histórico das características, deve ser possível visualizar botão para exportar dados sobre o produto.
- [x] Na aba de repositórios do produto, no gráfico de linha sobre as sub-características, deve ser possível visualizar botão para exportar dados sobre o produto.
- [x] Na aba de repositórios do produto, no gráfico de linha sobre as medidas, deve ser possível visualizar botão para exportar dados sobre o produto.
- [x] Na aba de repositórios do produto, no gráfico de linha sobre as métricas, deve ser possível visualizar botão para exportar dados sobre o produto.

**Funcionalidade Esperada**

- [x] Na aba de visão geral do produto, no gráfico de linha sobre o comportamento observado do produto, deve ser possível clicar no botão para exportar dados sobre o produto.
- [x] Na aba de repositórios do produto, no gráfico de linha sobre o histórico das características, deve ser possível clicar no botão para exportar dados sobre o produto.
- [x] Na aba de repositórios do produto, no gráfico de linha sobre as sub-características, deve ser possível clicar no botão para exportar dados sobre o produto.
- [x] Na aba de repositórios do produto, no gráfico de linha sobre as medidas, deve ser possível clicar no botão para exportar dados sobre o produto.
- [x] Na aba de repositórios do produto, no gráfico de linha sobre as métricas, deve ser possível clicar no botão para exportar dados sobre o produto.

**Comportamento Esperado**

- [ ] Ao clicar no botão na aba de visão geral do produto, no gráfico de linha sobre o comportamento observado do produto, deve ser baixado na máquina do usuário um arquivo CSV com os dados do gráfico levando em consideração o filtro por data selecionado pelo usuário.
- [ ] Ao clicar no botão na aba de repositórios do produto, no gráfico de linha sobre o histórico das características, deve ser baixado na máquina do usuário um arquivo CSV com os dados do gráfico levando em consideração o filtro por data selecionado pelo usuário.
- [ ] Ao clicar no botão na aba de repositórios do produto, no gráfico de linha sobre as sub-características, deve ser baixado na máquina do usuário um arquivo CSV com os dados do gráfico levando em consideração o filtro por data selecionado pelo usuário.
- [ ] Ao clicar no botão na aba de repositórios do produto, no gráfico de linha sobre as medidas, deve ser baixado na máquina do usuário um arquivo CSV com os dados do gráfico levando em consideração o filtro por data selecionado pelo usuário.
- [ ] Ao clicar no botão na aba de repositórios do produto, no gráfico de linha sobre as métricas, deve ser baixado na máquina do usuário um arquivo CSV com os dados do gráfico levando em consideração o filtro por data selecionado pelo usuário.

## Protótipo

>> Botão para exportar dados sobre o produto

![msg](https://github.com/fga-eps-mds/2023.2-MeasureSoftGram-DOC/assets/54439337/ee6191af-f91f-48e2-9816-08f6951c305d)

>> Gráfico na aba de visão geral do produto sobre o comportamento observado do produto

![Captura de tela de 2023-10-31 22-30-01](https://github.com/fga-eps-mds/2023.2-MeasureSoftGram-DOC/assets/54439337/5636a60b-f899-4c81-a056-63d08e1ae730)

>> Gráfico na aba de repositórios do produto sobre o histórico das características

![Captura de tela de 2023-10-31 22-29-22](https://github.com/fga-eps-mds/2023.2-MeasureSoftGram-DOC/assets/54439337/e0dbb26b-c9ef-4eb7-a075-448b76c361b7)

>> Gráfico na aba de repositórios do produto sobre as sub-características

![Captura de tela de 2023-10-31 22-29-30](https://github.com/fga-eps-mds/2023.2-MeasureSoftGram-DOC/assets/54439337/ef94bad5-172d-45a0-9649-53d80f7712ec)

>> Gráfico na aba de repositórios do produto sobre as medidas

![Captura de tela de 2023-10-31 22-29-38](https://github.com/fga-eps-mds/2023.2-MeasureSoftGram-DOC/assets/54439337/1dd51856-7603-414d-bbd8-fa5fe35efb93)

>> Gráfico na aba de repositórios do produto sobre as métricas

![Captura de tela de 2023-10-31 22-29-45](https://github.com/fga-eps-mds/2023.2-MeasureSoftGram-DOC/assets/54439337/982ee249-9a67-404b-a1a5-2ad41e9d8c8c)

**Comment by oCaioOliveira** [comment]
O protótipo está sendo implementado e em breve será anexado um link referenciando-o.

**Comment by oCaioOliveira** [comment]
Segundo o conversado na reunião do dia 08/11/2023 com o usuário Hilmer, foi decidido que essa atividade não será entrega com o filtro por data implementado na exportação de dados em um arquivo CSV em todos os gráficos. Foi dedicado uma sprint apenas para implementar essa funcionalidade, e foi concluído que o filtro por data não será possível ser implementado usando o componente de gráfico atual. Tendo em vista que, o componente que gera os gráficos do projeto estão usando uma biblioteca que já não é atualizada a mais de ano, foi decidido com o usuário que o melhor seria trocar o componente de gráfico para um mais atualizado e com mais suporte, e implementar um filtro por data que funcione como o necessário para filtrar na exportação de dados em arquivo CSV.
